## Restringir codecs bluetooth a AAC (estabilidade com AirPods Pro 2)
## SBC-XQ (~500kbps) sobrecarrega o adaptador e coincide com falhas HCI

monitor.bluez.properties = {
  bluez5.codecs = [ aac ]
  bluez5.enable-msbc = true
  bluez5.enable-hw-volume = true
}
