## AirPods Pro 2 (14:28:76:B1:5A:93) - estabilidade
## AAC nativo (mais estavel que SBC-XQ neste adaptador), hw volume, sem suspend

monitor.bluez.rules = [
  {
    matches = [
      {
        device.name = "bluez_card.14_28_76_B1_5A_93"
      }
    ]
    actions = {
      update-props = {
        bluez5.codecs = [ aac ]
        bluez5.enable-msbc = true
        bluez5.enable-hw-volume = true
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
